name: deploy

on:
  push:
    branches: [main]
    paths:
      - renv.lock
      - src/**
  workflow_dispatch:

jobs:
  deploy-to-connect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: renv

      - name: Setup dependencies
        env:
          TOKEN: ${{ secrets.CONNECT_TOKEN }}
          SECRET: ${{ secrets.CONNECT_SECRET }}
        run: |
          Rscript -e "install.packages(c('renv', 'rsconnect'))"
          Rscript -e "rsconnect::setAccountInfo(name='stlm', token='${TOKEN}', secret='${SECRET}')"

      - name: Activate renv environment
        shell: Rscript {0}
        run: |
          options(renv.config.repos.override=c(RSPM="https://packagemanager.posit.co/cran/__linux__/jammy/latest"))
          renv::restore()

      - name: Deploy to Posit Connect
        shell: Rscript {0}
        run: rsconnect::deployApp('./src', appName='my-first-shiny-app', forceUpdate=TRUE)
