name: deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-to-connect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: renv
