name: deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-to-connect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: renv

      - name: Setup dependencies
        shell: Rscript {0}
        run: |
          install.packages(c('renv', 'rsconnect'))
          rsconnect::setAccountInfo(name='stlm', token='35C637AD0E674D3A1C2208F00F7B8406', secret='4WhDhLinQ9QoQwflE4opF3nrUEXV4DAASTOIibGs')

      - name: Activate renv environment
        shell: Rscript {0}
        run: |
          options(renv.config.repos.override=c(RSPM="https://packagemanager.posit.co/cran/__linux__/jammy/latest"))
          renv::restore()

      - name: Deploy to Posit Connect
        shell: Rscript {0}
        run: rsconnect::deployApp('./src', appName='my-first-shiny-app', forceUpdate=TRUE)
