name: deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-to-connect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: renv

      - name: Setup dependencies
        run: |
          Rscript -e "install.packages(c('renv', 'rsconnect'))"
          Rscript -e "rsconnect::setAccountInfo(name='stlm', token='35C637AD0E674D3A1C2208F00F7B8406', secret='4WhDhLinQ9QoQwflE4opF3nrUEXV4DAASTOIibGs')"

      - name: Activate renv environment
        run: Rscript -e "renv::activate()"

      - name: Deploy to Posit Connect
        run: Rscript -e "rsconnect::deployApp('./src', appName='my-first-shiny-app')"
